import type { Metadata } from "next";
import localFont from "next/font/local";
import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const gendra = localFont({
  src: "./fonts/gendra.woff2",
  weight: "400",
  variable: "--font-gendra",
  display: "swap",
});

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Vidzashop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.variable} ${gendra.variable}`}>
      <body>
        <Navbar/>
        <main>{children}</main>
      </body>
    </html>
  );
}
